### PR TITLE
feat(select): allow custom value and label arguments

### PR DESCRIPTION
**Pull request by velrest**

### CODE REVIEW

**Comment by luytena** [comment]
While we're at it, is there any case where we need to support the regular array of strings options (no objects)?

**Comment by velrest** [comment]
@luytena  Actually should we use a separate argument for this kind of magic `options`? So we can leave the default `options` arg as expected?

**Comment by luytena** [comment]
@velrest That sounds like a good idea, it might lead to confusion in the future otherwise

**Review by luytena — APPROVED** [review]

**Pull request merged**
